### ISSUE TITLE
onlyif_cmds_exist should get a kwarg to fail when on CI services

### ISSUE THREAD

**Issue by jankatins** [ipython/ipython_genutils#7]
In this case the an incomplete latex setup on travis lead to missing tests in nbconvert, which prevented the tests from registering a bug. See https://github.com/jupyter/nbconvert/pull/356 for the story...

IMO a testsuite should not skip any tests in a CI environment, so it would be nice if the decorator could raise a failure instead of skipping if it is run on a CI service (=change the default to fail if the command is not present on travis/appveyor/circleci).

CI like travis set some environment variables, so a simple test for such env variables could be used to change a skip to a fail.

**Comment by takluyver** [comment]
I think previously it was harder to install things like Tex on Travis, which was why we had some skipped tests.

I don't think I'd go for checking for specific CI services, but rather I'd allow setting some environment variable like `FAIL_ON_TEST_SKIP=1`. Maybe nose/py.test already support an option for something like this?

**Comment by jankatins** [comment]
I asked for pytest on twitter, but it seems they don't have such an switch. https://twitter.com/janschulz/status/763650601796395008

**Comment by takluyver** [comment]
It sounds like it should be doable as a py.test plugin rather than changing project code, though. Based on [this gist](https://gist.github.com/hackebrot/491452892292646cb6d83a5c2f653739) in a response.

Nose has a `--no-skip` [option](http://nose.readthedocs.io/en/latest/man.html#cmdoption--no-skip) which I imagine would do what we want.
